# mertree

`mertree` (mixed-effects regression trees) is an alternative implementation of `REEMtree` (Sela and Simonoff, 2012) and `REEMctree` (Fu and Simonoff, 2014) that uses `lme4` (Bates, et al., 2015) for efficient computation of mixed-effects models with large data sets.

## Installation
Package `mertree` is not currently available from CRAN, but the development version is hosted on GitHub at https://github.com/bgreenwell/mertree and can be downloaded using [`devtools`](https://github.com/hadley/devtools):
```r
# Assuming devtools is already installed
devtools::install_github("bgreenwell/mertree")
```
Bug reports should be submitted to https://github.com/bgreenwell/mertree/issues.

## References

Rebecca J. Sela and Jeffrey S. Simonoff (2012). "RE-EM Trees: A Data Mining Approach for Longitudinal and Clustered Data". _Machine Learning_, 86(2), 169-207.

Wei Fu and Jeffrey S. Simonoff (2015), "Unbiased Regression Trees for Longitudinal and Clustered Data". _Computational Statistics and Data Analysis_, 88, 53-74.

Douglas Bates, Martin Maechler, Ben Bolker, Steve Walker (2015). "Fitting Linear Mixed-Effects Models Using lme4". _Journal of Statistical Software_, 67(1), 53-74. doi:10.18637/jss.v067.i01.


